platformName: Android
platformVersion: 7.1.2
deviceIP: 127.0.0.1
devicePort: 21503
app: automation/app/cn/apk/经纪人测试.apk
appPackage: com.easylife.house.broker.test
appActivity: com.easylife.house.broker.ui.MainActivity
noReset: False
unicodeKeyboard: True
resetKeyboard: True
automationName: uiautomator2
img:
report:
data:







